config/routes.rb
VisualPortfolio::Application.routes.draw do
  root :to => "werks#index"
  resources :werks

end

app/models/werk.rb
class Werk
  include Mongoid::Document
  # include Mongoid::Paperclip
  field :name
  field :info
  field :url
  # has_mongoid_attached_file :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/werks_controller.rb
class WerksController < ApplicationController
  before_action :set_werk, only: [:show, :edit, :update, :destroy]

  # GET /werks
  # GET /werks.json
  def index
    @werks = Werk.all
  end

  # GET /werks/1
  # GET /werks/1.json
  def show
  end

  # GET /werks/new
  def new
    @werk = Werk.new
  end

  # GET /werks/1/edit
  def edit
  end

  # POST /werks
  # POST /werks.json
  def create
    @werk = Werk.new(werk_params)

    respond_to do |format|
      if @werk.save
        format.html { redirect_to @werk, notice: 'Werk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @werk }
      else
        format.html { render action: 'new' }
        format.json { render json: @werk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /werks/1
  # PATCH/PUT /werks/1.json
  def update
    respond_to do |format|
      if @werk.update(werk_params)
        format.html { redirect_to @werk, notice: 'Werk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @werk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /werks/1
  # DELETE /werks/1.json
  def destroy
    @werk.destroy
    respond_to do |format|
      format.html { redirect_to werks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_werk
      @werk = Werk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def werk_params
      params[:werk]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/werks_helper.rb
module WerksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisualPortfolio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link type="text/css" href="http://lab.hakim.se/reveal-js/css/reveal.min.css" rel="stylesheet" media="all">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script type="text/javascript" src="http://lab.hakim.se/reveal-js/js/reveal.min.js">
  
</script>
 <script type="text/javascript" src="http://lab.hakim.se/reveal-js/js/reveal.min.js"></script>
    </body>
</html>
<script type="text/javascript">
  Reveal.initialize({

    // Display controls in the bottom right corner
    controls: true,

    // Display a presentation progress bar
    progress: true,

    // Push each slide change to the browser history
    history: true,

    // Enable keyboard shortcuts for navigation
    keyboard: true,

    // Enable the slide overview mode
    overview: true,

    // Vertical centering of slides
    center: true,

    // Loop the presentation
    loop: true,

    // Change the presentation direction to be RTL
    rtl: false,

    // Number of milliseconds between automatically proceeding to the 
    // next slide, disabled when set to 0, this value can be overwritten
    // by using a data-autoslide attribute on your slides
    autoSlide: 5000,

    // Enable slide navigation via mouse wheel
    mouseWheel: false,

    // Apply a 3D roll to links on hover
    rollingLinks: true,

    // Transition style
    transition: 'default' // default/cube/page/concave/zoom/linear/fade/none

  }); 
</script>
</body>
</html>

app/views/werks/_form.html.erb
<%= form_for(@werk) do |f| %>
  <% if @werk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@werk.errors.count, "error") %> prohibited this werk from being saved:</h2>

      <ul>
      <% @werk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.label :url %>
      <%= f.url_field :url %>
    </li>      
    <li>
      <%= f.label "any other information" %>
      <%= f.text_area :info, size: "60x12" %>
    </li>
  </ul>      

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/werks/edit.html.erb
<h1>Editing werk</h1>

<%= render 'form' %>

<%= link_to 'Show', @werk %> |
<%= link_to 'Back', werks_path %>

app/views/werks/index.html.erb
<div class="reveal">
  <div class="slides">
    <% @werks.each do |werk| %>
      <section>
        <figure><%= image_tag werk.url %></figure>
        <figcaption> 
          <h2><%=werk.name%></h2>
          <%=werk.info%>
        </figcaption>
      </section>
    <% end %>
  </div>
</div>

app/views/werks/new.html.erb
<h1>New werk</h1>

<%= render 'form' %>

<%= link_to 'Back', werks_path %>

app/views/werks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_werk_path(@werk) %> |
<%= link_to 'Back', werks_path %>